### PR TITLE
Add new plugin: AnyVideo Downloader

### PR DESCRIPTION
**Pull request by z1nc0r3**
Plugin for downloading videos from YouTube, Facebook, Twitter, Instagram, and many other websites.

### CODE REVIEW

**Review by Garulf — CHANGES_REQUESTED** [review]
Flow Launcher uses Embedded Python 3.11 by default. Your release CI is using Python 3.10. 

Please update your GitHub workflow to use this version. If your plugin has any non-native Python code this may cause issues for users.

**Comment by z1nc0r3** [comment]
Done ✅

**Comment by Garulf** [comment]
@z1nc0r3 I see the change, however you may want to initiate a release with the updated workflow.

**Comment by z1nc0r3** [comment]
Yeah, already ran a release workflow

**Comment by Garulf** [comment]
Yeah I see that now sorry. 

image

Wonder why this timestamp didn't update 🤔

**Comment by Garulf** [comment]
Looks awesome!

**Comment by z1nc0r3** [comment]
I think the workflow only updates the asset files if there is already a release for that tag. I can see the zip file time is updated.

**Pull request merged**
