### PR TITLE
Add Hello World Node.js example plugin project

### PR DESCRIPTION
**Pull request by jjw24**
Add Hello World Node.js example plugin project

### CODE REVIEW

**Comment by jjw24** [comment]
@Garulf can we skip the python plugin test for executables please. also i think the error message meant to say 'Could not find Tested on the plugin?'

**Comment by Garulf** [comment]
> @Garulf can we skip the python plugin test for executables please. https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/runs/4630606159?check_suite_focus=true also i think the error message meant to say 'Could not find Tested on the plugin'?

Ah! whoops! I must have removed the language check by mistake?

**Comment by Garulf** [comment]
Fixed: https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/pull/112

**Comment by jjw24** [comment]
LOL damn. we both added a fix...

**Comment by Garulf** [comment]
> LOL damn. we both added a fix...

LOL been meaning to add a fix but couldnt think of a "proper" way to add until now.

**Comment by jjw24** [comment]
i will revert mine

**Comment by Garulf** [comment]
Looks like it tested with the old version

**Comment by jjw24** [comment]
just merged main. Please review while i have you.

**Comment by Garulf** [comment]
Damn it raised a KeyValue exception.. one moment

**Comment by Garulf** [comment]
Fixed: https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/pull/113

**Review by Garulf — APPROVED** [review]

**Pull request merged**
