### PR TITLE
Correct requirements pathing

### PR DESCRIPTION
**Pull request by Garulf**

### CODE REVIEW

**Comment by taooceros** [comment]
why need to specify branch?

**Comment by Garulf** [comment]
Oh thats not a branch. Because we're working with the repo and plugin I have them seperated. This repo is checked out to `main` and the plugin release is added to `plugin`.

**Comment by taooceros** [comment]
oh I get you

**Comment by Garulf** [comment]
Actually we don't even need to do that. It's faster and easier to checkout to the current working directory and have the plugin in a sub folder.

**Comment by taooceros** [comment]
yes no need to do so

**Review by taooceros — APPROVED** [review]

**Comment by Garulf** [comment]
Possible to force?

**Comment by taooceros** [comment]
@jjw24

**Comment by taooceros** [comment]
> > Possible to force?
> 
> @Garulf sorry what do you mean?

hold on wait him add the fix for the unrun test.

**Comment by Garulf** [comment]
> > Possible to force?
> 
> @Garulf sorry what do you mean?

PR wont merge because it can't pass `test-python` workflow (which should only trigger if plugins.json is changed in the PR).

**Comment by taooceros** [comment]
> > > Possible to force?
> > 
> > 
> > @Garulf sorry what do you mean?
> 
> PR wont merge because it can't pass `test-python` workflow (which should only trigger if plugins.json is changed in the PR).

Fix that here

**Comment by Garulf** [comment]
I got it. One moment.

**Comment by Garulf** [comment]
Looks like it's running correctly.

**Review by jjw24 — APPROVED** [review]

**Pull request merged**
