### PR TITLE
Add link checker github action

### PR DESCRIPTION
**Pull request by JohnTheGr8**
Added a Github action that checks every link in the `plugins.json` file whenever the file is updated (push or PR).

The action also runs on a cron schedule so that we get alerted if one of the plugin repositories goes down.

I've also fixed 3 links that were broken.

### CODE REVIEW

**Comment by Garulf** [comment]
I have similar check added in my PR https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/pull/246

**Comment by JohnTheGr8** [comment]
> I have similar check added in my PR #246

sorry I didn't notice... but regardless I think using a dedicated tool for this is a more elegant solution ;)

**Comment by Garulf** [comment]
> > I have similar check added in my PR #246
> 
> sorry I didn't notice... but regardless I think using a dedicated tool for this is a more elegant solution ;)

The solution is good, however I'd like to check URLs on submission as well. 

I am for whatever works best.

**Comment by JohnTheGr8** [comment]
> The solution is good, however I'd like to check URLs on submission as well.

it does, I made it run on push, PR and on a schedule. Am I missing something? (not very familiar with github actions)

**Comment by Garulf** [comment]
> also runs on a cron schedule

Sorry I misread and thought it only ran on cron

**Comment by JohnTheGr8** [comment]
> Sorry I misread and thought it only ran on cron

I mean the check did run on this PR 😂

**Comment by Garulf** [comment]
Will this fail a submission if someone else's link is dead?

**Comment by JohnTheGr8** [comment]
> Will this fail a submission if someone else's link is dead?

I think we can configure what checks must be green before a PR can be merged...

**Comment by Garulf** [comment]
> I think we can configure what checks must be green before a PR can be merged...

IIRC its all or nothing with github tests

**Comment by JohnTheGr8** [comment]
> IIRC its all or nothing with github tests

well, shouldn't be an issue, there's just 3 dead links after all this time...

**Review by Garulf — APPROVED** [review]

**Pull request merged**
