### PR TITLE
Added my new IP plugin

### PR DESCRIPTION
**Pull request by Echostorm44**
added new plugin for just getting 1 public and 1 real private IP

### CODE REVIEW

**Comment by taooceros** [comment]
Just a bit curious, do we have any functionality difference with this one? https://github.com/taooceros/Flow.Plugin.IPAddress

**Comment by Echostorm44** [comment]
Yeah, theirs just pulls all the local IPs including virtual ones from stuff like HyperV, VMware, docker etc.  They also don't pull your public IP.  Mine only pulls your real LAN IP and your public IP.

**Comment by taooceros** [comment]
> Yeah, theirs just pulls all the local IPs including virtual ones from stuff like HyperV, VMware, docker etc so you can't tell whats what. They also don't pull your public IP. Mine only pulls your real LAN IP and your public IP.

Sure thanks. Though as what I remember that plugin also trying to fetch the public IP (I think something is not working correctly though). Do you mind adding your code in that plugin instead of adding a new plugin for a similar purpose? I feel like that may create some confusion for user to choose from. (It's totally up to you. I will be happy to merge this one).

**Comment by Echostorm44** [comment]
If it's all the same to you I'd rather keep mine so that I can maintain it and keep the functionality cleaner than the other one.

**Comment by taooceros** [comment]
Sure thing

**Review by taooceros — APPROVED** [review]

**Pull request merged**
