### PR TITLE
Add Bitwarden Plugin

### PR DESCRIPTION
**Pull request by RedMageKnight**
Would like to contribute new plugin for accessing your Bitwarden vault from Flow Launcher!

### CODE REVIEW

**Comment by Garulf** [comment]
Hi @RedMageKnight, the plugin looks very good! 

We tend to scrutinize plugins that deal with security for obvious reasons, we also ask that all plugins implement CI/CD releases. Please have a look at other CSharp plugins for an example.

**Review by Garulf — CHANGES_REQUESTED** [review]
Hi @RedMageKnight, the plugin looks very good! 

We tend to scrutinize plugins that deal with security for obvious reasons, we also ask that all plugins implement CI/CD releases. Please have a look at other CSharp plugins for an example.

**Review by RedMageKnight — COMMENTED** [review]
Hi @Garulf! Thank you very much! I went ahead and added the CI/CD workflows to my repository so it should be good! 

Updating the pull request for this branch to update my UrlDownload value since I changed it to conform a bit better with the rest of my project. 

Let me know if you need anything else from me!

**Review by Garulf — APPROVED** [review]

**Comment by Garulf** [comment]
Looks all good to me!

**Pull request merged**
