### PR TITLE
Add Desktop Cleanup plugin

### PR DESCRIPTION
**Pull request by umi-uyura**
Delete files and folders on desktop plugin.

My primary use is to delete shortcuts that are created when I install applications.

### CODE REVIEW

**Comment by taooceros** [comment]
hmm it doesn't work for me. I am on win11 and no log is caught. @Garulf would you give it a test?

**Comment by Garulf** [comment]
On initial review nothing occurs when an option is selected. Also seeing no output in the log as to what may be happening.

**Comment by umi-uyura** [comment]
@taooceros Sorry, I don't have Windows 11, so I haven't tested it.
I'm only testing on my Windows 10.
I will get Windows 11 and test it.

**Comment by taooceros** [comment]
> @taooceros Sorry, I don't have Windows 11, so I haven't tested it.
> I'm only testing on my Windows 10.
> I will get Windows 11 and test it.
> 

I think @Garulf is on win 10, so probably it's not win 11 issue.

**Comment by umi-uyura** [comment]
I tried it on another Windows 10 PC, and it worked as intended.
I installed and run the plugin using the following steps. Is there any difference?

* Download [ZIP file](https://github.com/umi-uyura/Flow.Launcher.Plugin.DesktopCleanup/releases/download/v1.0.0/Flow.Launcher.Plugin.DesktopCleanup-1.0.0.zip) from GitHub Releases
* Extract ZIP file to `%USERPROFILE%\AppData\Roaming\FlowLauncher\Plugins` 
* Restart Flow Launcher
* Run `dc clean` at the Flow Launcher

Flow Launcher version: 1.9.1

**Comment by taooceros** [comment]
oh I think I understand why it doesn't work for me before. I only type `dc` and select the result of clean/trash. I guess you can fix that.

**Comment by umi-uyura** [comment]
Thank you, I think I understand the problem too.
I will try to fix it.

**Review by taooceros — APPROVED** [review]

**Review by taooceros — DISMISSED** [review]

**Review by taooceros — APPROVED** [review]
lol thank you for merging

**Pull request merged**
