### PR TITLE
Adding GUID generation

### PR DESCRIPTION
**Pull request by cfe84**
This is a node plugin that allows generating GUIDs from flow launcher

### CODE REVIEW

**Comment by taooceros** [comment]
I guess you need to extract the .wox file inside the zip file to make this plugin works for flow.

**Review by jjw24 — CHANGES_REQUESTED** [review]
please see Tao's comment

**Comment by cfe84** [comment]
> I guess you need to extract the .wox file inside the zip file to make this plugin works for flow.

Thanks, updated the zip to zip the folder instead of the .wox

**Review by jjw24 — CHANGES_REQUESTED** [review]
Hey I just tested out this plugin, it's erroring out. Could you have a look please.

You can test this plugin directly with `pm install <url to your plugin zip>` also you can follow this example plugin `pm install node`.

Additionally:
1. Since we have yet implemented direct download of node.js, could you indicate in your readme the requirement for this plugin- where to download the node.js installer.
2. I know it's listed in the manifest's description as generate guid from flow launcher, would it be possible to also indicate in your repo that it is also for Flow Launcher, so users don't get confused.

**Comment by jjw24** [comment]
Hey @cfe84, any updates on this?

**Comment by Garulf** [comment]
Closing due to inactivity. Please feel free to reopen.

**Pull request closed without merging**
