### PR TITLE
Add AudFlow, Statis, CkFlow, QrFlow and DdFlow plugins

### PR DESCRIPTION
**Pull request by asmpro7**
text to speech plugin

### CODE REVIEW

**Comment by asmpro7** [comment]
it's stasis stands for statistics 🤦‍♂️ 
but any thing😁

**Comment by VictoriousRaptor** [comment]
Statis tested. Don't have any more time today. will do it later.

**Comment by asmpro7** [comment]
ok, take your time 
i work on anthor two plugins, when i finish i pull request them 🫡

**Review by VictoriousRaptor — APPROVED** [review]

**Comment by asmpro7** [comment]
the 5 plugin merged?
if i want to make an simple edit in one readme because a typo ,i should PR the plugin again ?😅

**Comment by VictoriousRaptor** [comment]
> the 5 plugin merged? if i want to make an simple edit in one readme because a typo ,i should PR the plugin again ?😅

By readme do you mean the description in the json? If so, yes.

**Comment by asmpro7** [comment]
no in my plugin readme not here

**Comment by VictoriousRaptor** [comment]
> no in my plugin readme not here

Then you don't have to. Publish a release and updates are automatically done (see readme of this repo).

**Comment by asmpro7** [comment]
Thank you very much, 
it simple typo There is no need to update it😊
  thank you for hard work 🫡

**Pull request merged**
