### PR TITLE
update python plugin tests 

### PR DESCRIPTION
**Pull request by jjw24**
tested python plugins, update the plugin list.

### CODE REVIEW

**Comment by jjw24** [comment]
@Garulf i removed the 'Tested' field so it can re-test, but seems to indicate no issues with plugins, even with RollDice. Have I not done the test correctly?

**Comment by Garulf** [comment]
After staring at the same code for 30 minutes I finally noticed what was missing. Fixed in https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/pull/105

**Comment by Garulf** [comment]
I should mention I never imagined multiple plugins being submitted at once. The Python testing only runs on the first plugin without a tested field.

**Comment by jjw24** [comment]
Nah, keep it how it is should be fine, I'm just trying to find an easier way to test run the current plugins instead of manually download and run each one.

**Comment by Garulf** [comment]
Hmm.. encoding error failure?

**Comment by Garulf** [comment]
Hmm I wonder if we could winget flow launcher in the CI. Should fix Flox erroring out.

**Comment by Garulf** [comment]
Sorry hijacked to get Flox working

**Review by Garulf — APPROVED** [review]

**Pull request merged**
