### PR TITLE
update Everything plugin

### PR DESCRIPTION
**Pull request by jjw24**

### CODE REVIEW

**Review by taooceros — APPROVED** [review]

**Comment by taooceros** [comment]
What are these tests doing?

**Comment by jjw24** [comment]
> What are these tests doing?

CI checks:
https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/pull/9

**Comment by taooceros** [comment]
Why do we need to test it with both python 3.7 and 3.8?

**Comment by Zeroto521** [comment]
It’s possible I would like to test with all kinds of python versions to ensure no problem. Py3.7 and Py3.8 have a very tiny changes.

**Comment by taooceros** [comment]
But the question is that we are not testing whether the plugin is runnable with python, but whether the json format is valid, so Py3.7 and Py3.8 should not have difference.

**Pull request merged**
