### PR TITLE
add Hello World Python plugin

### PR DESCRIPTION
**Pull request by jjw24**
Add Hello World Python plugin

### CODE REVIEW

**Comment by Garulf** [comment]
This has node hello world plugin included to?

**Comment by jjw24** [comment]
nah this has the Hello World Python plugin

**Comment by Garulf** [comment]
> nah this has the Hello World Python plugin

Strange I was seeing

> nah this has the Hello World Python plugin

Strange Github was showing multiple entries

**Comment by jjw24** [comment]
shouldnt be, just pushed latest origin, please re-review.

**Review by onesounds — APPROVED** [review]

**Pull request merged**
