### PR TITLE
Add statis Plugin

### PR DESCRIPTION
**Pull request by asmpro7**
Add statis Plugin
https://github.com/asmpro7/StatisFlow

### CODE REVIEW

**Comment by asmpro7** [comment]
@Garulf is any thing wrong? 
tell me to fix  🫡

**Comment by asmpro7** [comment]
is there any thing wrong ?

**Review by VictoriousRaptor — CHANGES_REQUESTED** [review]
Please solve the coflicts. But I suggest you open a new PR based on plugin_api_v2 branch instead. 
Plugin's tested and running.

**Comment by asmpro7** [comment]
ok i will close it and add new PR

**Pull request closed without merging**
