### PR TITLE
Notion Search API Updated Version v1.0.1

### PR DESCRIPTION
**Pull request by MinYn**
1. added Language
2. update package pyflowlauncher
3. browser open bug resolve

[https://github.com/MinYn/flow-launcher-notion-plugin/pull/2](https://github.com/MinYn/flow-launcher-notion-plugin/pull/2)

### CODE REVIEW

**Comment by NoPlagiarism** [comment]
Already updated in https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/commit/6dfa24c4e67cadae13d7299e01e745ad9036d2b8

CI is autoupdatable

**Comment by MinYn** [comment]
@NoPlagiarism aha okay thank you this pr please decline

**Comment by NoPlagiarism** [comment]
You can close it yourself by clicking on "`Close Pull Request`"

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/closing-a-pull-request

**Comment by MinYn** [comment]
@NoPlagiarism thx closed pr

**Pull request closed without merging**
