### PR TITLE
Add new plugin One-time Password

### PR DESCRIPTION
**Pull request by GoodbyeNJN**
https://github.com/GoodbyeNJN/Flow.Launcher.Plugin.OneTimePassword

lib list:
- Flow.Launcher.Plugin@4.1.1
- Otp.NET@1.3.0

### CODE REVIEW

**Comment by VictoriousRaptor** [comment]
Please resolve conflicts.

**Comment by GoodbyeNJN** [comment]
> Please resolve conflicts.

done

**Comment by GoodbyeNJN** [comment]
@VictoriousRaptor Could you please push forward this PR?

**Review by taooceros — APPROVED** [review]

**Comment by taooceros** [comment]
Looks very interesting. Thanks

**Pull request merged**
