### PR TITLE
add sharex plugin

### PR DESCRIPTION
**Pull request by dufguix**

### CODE REVIEW

**Comment by jjw24** [comment]
Hi there, could you please add a GitHub workflow and publish your release this way. FYI can follow this one - https://github.com/taooceros/Flow.Plugin.WindowWalker/blob/master/.github/workflows/publish-action.yml

**Comment by dufguix** [comment]
It should be ok now.

**Comment by jjw24** [comment]
Could you also delete the old artifact please image

**Comment by jjw24** [comment]
Also just made an update to the filename to be {name}-{guid}.json otherwise there maybe issues down the track with the CI.

**Comment by dufguix** [comment]
Old artifact removed.

I see you have already renamed the file.

**Review by jjw24 — APPROVED** [review]

**Pull request merged**
