### PR TITLE
Add Visual Studio Plugin

### PR DESCRIPTION
**Pull request by Odotocodot**
[Repository](https://github.com/Odotocodot/VisualStudio4Flow)

Example Pic
default_search

### CODE REVIEW

**Comment by KrystianLesniak** [comment]
I see "Check links" job failed because of my plugin:
image

I've merged some restructuring of directories today and I totally forgot icon URL with path is directly in plugin.json file and should not be moved. I've just applied quick-fix and returned icon.png to a proper place so after re-running job, all checks should pass.

P.S. Great plugin you made here 👍

**Comment by Odotocodot** [comment]
Thanks for the quick fix! Hopefully it will get a re-run soon 😉.

P.S.  Thanks! I also instantly grabbed your game launcher when i saw it 😄, works like a charm!

> I see "Check links" job failed because of my plugin: image
> 
> I've merged some restructuring of directories today and I totally forgot icon URL with path is directly in plugin.json file and should not be moved. I've just applied quick-fix and returned icon.png to a proper place so after re-running job, all checks should pass.
> 
> P.S. Great plugin you made here 👍

**Comment by Garulf** [comment]
Looks like the test failed because your icon URL is down or incorrect.

**Comment by Odotocodot** [comment]
Hey, yeah its as Kyrstain said their link is was incorrect at the time of running the test

**Comment by Garulf** [comment]
> Hey, yeah its as Kyrstain said their link is was incorrect at the time of running the test

I re-ran the test and the URL is still not working. Please commit the correct URL and I'll happily rerun the tests.

**Comment by Odotocodot** [comment]
> > Hey, yeah its as Kyrstain said their link is was incorrect at the time of running the test
> 
> I re-ran the test and the URL is still not working. Please commit the correct URL and I'll happily rerun the tests.

Ah okay! Should be fixed now!

**Review by jjw24 — APPROVED** [review]

**Pull request merged**
