### PR TITLE
Add ElementFlow

### PR DESCRIPTION
**Pull request by asmpro7**
Data for all Chemical Elements

### CODE REVIEW

**Comment by VictoriousRaptor** [comment]
Please format the lines you added.

**Comment by VictoriousRaptor** [comment]
Just downloaded and got the following errors. Am I missing something?
```

Please open new issue in: https://github.com/asmpro7/ElementFlow/issues
1. upload log file: C:\Users\flame\AppData\Roaming\FlowLauncher\Logs\1.0.0\2023-05-17.txt
2. copy below exception message

Flow Launcher version: 1.0.0
OS Version: 19045.2846
IntPtr Length: 8
x64: True

Python Path: C:\Program Files\Python311\pythonw.exe
Node Path: 
Date: 05/17/2023 08:57:01
Exception:
ElementFlow Exception: 
Websites: https://github.com/asmpro7/ElementFlow
Author: Ahmed ElSaeed
Version: 1.0.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\flame\AppData\Roaming\FlowLauncher\Plugins\ElementFlow-59a2aa4a-d91e-488e-bd54-bbc05e872da3\main.py", line 13, in <module>
    from PIL import Image
  File "C:\Users\flame\AppData\Roaming\FlowLauncher\Plugins\ElementFlow-59a2aa4a-d91e-488e-bd54-bbc05e872da3\lib\PIL\Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (C:\Users\flame\AppData\Roaming\FlowLauncher\Plugins\ElementFlow-59a2aa4a-d91e-488e-bd54-bbc05e872da3\lib\PIL\__init__.py)

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\flame\AppData\Roaming\FlowLauncher\Plugins\ElementFlow-59a2aa4a-d91e-488e-bd54-bbc05e872da3\main.py", line 13, in <module>
    from PIL import Image
  File "C:\Users\flame\AppData\Roaming\FlowLauncher\Plugins\ElementFlow-59a2aa4a-d91e-488e-bd54-bbc05e872da3\lib\PIL\Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (C:\Users\flame\AppData\Roaming\FlowLauncher\Plugins\ElementFlow-59a2aa4a-d91e-488e-bd54-bbc05e872da3\lib\PIL\__init__.py)

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in D:\Programming\Flow.Launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in D:\Programming\Flow.Launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in D:\Programming\Flow.Launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in D:\Programming\Flow.Launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in D:\Programming\Flow.Launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in D:\Programming\Flow.Launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in D:\Programming\Flow.Launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass145_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in D:\Programming\Flow.Launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 937
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in D:\Programming\Flow.Launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 901
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by VictoriousRaptor** [comment]
Just downloaded and got the following errors. Am I missing something?
```

Please open new issue in: https://github.com/asmpro7/ElementFlow/issues
1. upload log file: C:\Users\***\AppData\Roaming\FlowLauncher\Logs\1.0.0\2023-05-17.txt
2. copy below exception message

Flow Launcher version: 1.0.0
OS Version: 19045.2846
IntPtr Length: 8
x64: True

Python Path: C:\Program Files\Python311\pythonw.exe
Node Path: 
Date: 05/17/2023 08:57:01
Exception:
ElementFlow Exception: 
Websites: https://github.com/asmpro7/ElementFlow
Author: Ahmed ElSaeed
Version: 1.0.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\***\AppData\Roaming\FlowLauncher\Plugins\ElementFlow-59a2aa4a-d91e-488e-bd54-bbc05e872da3\main.py", line 13, in <module>
    from PIL import Image
  File "C:\Users\***\AppData\Roaming\FlowLauncher\Plugins\ElementFlow-59a2aa4a-d91e-488e-bd54-bbc05e872da3\lib\PIL\Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (C:\Users\***\AppData\Roaming\FlowLauncher\Plugins\ElementFlow-59a2aa4a-d91e-488e-bd54-bbc05e872da3\lib\PIL\__init__.py)

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\***\AppData\Roaming\FlowLauncher\Plugins\ElementFlow-59a2aa4a-d91e-488e-bd54-bbc05e872da3\main.py", line 13, in <module>
    from PIL import Image
  File "C:\Users\***\AppData\Roaming\FlowLauncher\Plugins\ElementFlow-59a2aa4a-d91e-488e-bd54-bbc05e872da3\lib\PIL\Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (C:\Users\***\AppData\Roaming\FlowLauncher\Plugins\ElementFlow-59a2aa4a-d91e-488e-bd54-bbc05e872da3\lib\PIL\__init__.py)

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in D:\Programming\Flow.Launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in D:\Programming\Flow.Launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in D:\Programming\Flow.Launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in D:\Programming\Flow.Launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in D:\Programming\Flow.Launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in D:\Programming\Flow.Launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in D:\Programming\Flow.Launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass145_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in D:\Programming\Flow.Launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 937
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in D:\Programming\Flow.Launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 901
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by asmpro7** [comment]
yeb the problem with version of python you use, it work on 3.8 and you use 3.11

**Comment by asmpro7** [comment]
you can also install pillow 9.5 manual I guess it will work

**Review by Garulf — APPROVED** [review]

**Pull request merged**
