### PR TITLE
update readme IcoPath explanation

### PR DESCRIPTION
**Pull request by jjw24**

### CODE REVIEW

**Comment by jjw24** [comment]
hmm @Zeroto521 @taooceros i thought the skip_check_job should skip modifications not made to plugins.json, doesnt seem to be the case:
https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/runs/4145198764?check_suite_focus=true

**Comment by Garulf** [comment]
At this point I'm wondering if we should just have devs add their repo URL to a CSV file and have an action on PR fetch the details.

**Comment by jjw24** [comment]
> At this point I'm wondering if we should just have devs add their repo URL to a CSV file and have an action on PR fetch the details.

This is actually with considering, just pull the data from the repo url provided.

**Comment by Garulf** [comment]
I'm doing some research & testing on this to see if its possible.

**Comment by jjw24** [comment]
> I'm doing some research & testing on this to see if its possible.

Although it's a 2 min job to copy and paste that information from plugin.json

**Comment by Garulf** [comment]
> > I'm doing some research & testing on this to see if its possible.
> 
> Although it's a 2 min job to copy and paste that information from plugin.json

True. But it leaves a lot of room for errors and its one of those situations where all the info is already there and available to grab so why not stream line it?

**Comment by taooceros** [comment]
Add use cdn is recommended may be good

**Comment by Garulf** [comment]
> Add use cdn is recommended may be good

See https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/pull/88/commits/76355a807cad2d054b9317d3230dd75d459bdc2d

**Review by Garulf — APPROVED** [review]

**Comment by Garulf** [comment]
Seems to be hung up by older version of python-plugin workflow...

**Pull request merged**
