### PR TITLE
Notion search

### PR DESCRIPTION
**Pull request by danielduckworth**
Added requests to requirements so it should work by installing from Flow Launcher now.

### CODE REVIEW

**Comment by jjw24** [comment]
The CI error just reminded me, I forgot to mention previously, it might be good to handle unauthorised exception thrown since the hotkey is `n` and you can run into this error if installed for the first time and not yet added the token.

**Comment by danielduckworth** [comment]
> The CI error just reminded me, I forgot to mention previously, it might be good to handle unauthorised exception thrown since the hotkey is `n` and you can run into this error if installed for the first time and not yet added the token.

Yep, good idea. Will do.

**Comment by jjw24** [comment]
You can return a result when a token is not set to let users know that they need to go to settings to add it.

**Comment by Garulf** [comment]
I ran into a few issues when running the plugin. I'll submit a PR with a fix in a moment.

**Comment by danielduckworth** [comment]
> I ran into a few issues when running the plugin. I'll submit a PR with a fix in a moment.

Hi @Garulf. I've added two try/except flows to handle an empty token setting and queries that return API errors. However the latter catches cases where the API returns no results without errors, yet the message to the user suggests there was an error. So I need to catch the actual error here to handle it more accurately.

The other problem is that in Flow Launcher, if I enter the action keyword (n) but do not enter a search term and wait, eventually it searches with an empty query which crashes because the helper function makes assumptions about the title key in the dictionary. Seems there might be a variation of the page result where the name key isn't used or used differently. I was thinking it might be better to enumerate the whole dictionary to return the values for the title keys rather than a fixed key/value pair which could change as the API endpoint changes.

**Comment by jjw24** [comment]
Hey @danielduckworth, any updates and ready to get published?

**Comment by danielduckworth** [comment]
Hey @jjw24 I've updated the plugin. I messed up the GitHub process and have accidently created a new pull requesting rather than resolving this. Not sure what happened.

https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/pull/155

**Comment by danielduckworth** [comment]
I'll try again

**Pull request closed without merging**
