### PR TITLE
use cdn instead of direct raw github icon path

### PR DESCRIPTION
**Pull request by taooceros**

### CODE REVIEW

**Comment by taooceros** [comment]
This will greatly help chinese user to load icon who don't use special setting for github.

**Review by onesounds — APPROVED** [review]

**Comment by Garulf** [comment]
How is this URL generated?

**Comment by jjw24** [comment]
They are CDN provider, check their website

**Comment by taooceros** [comment]
> How is this URL generated?

Replace github with their website by using str replace (regex command in nushell).

**Pull request merged**
