### PR TITLE
Add IcoPath

### PR DESCRIPTION
**Pull request by taooceros**
I fetch the raw github iconpath for all the plugins. We will support it in the plugin store.

### CODE REVIEW

**Comment by taooceros** [comment]
```python
import json
import requests

with open("plugins.json") as pluginsFile:
    plugins = json.load(pluginsFile)

for plugin in plugins:
    sourceCodeSplit = plugin["UrlSourceCode"].split("/")
    author = sourceCodeSplit[3]
    pluginName = sourceCodeSplit[4]

    print(author, pluginName)

    rawPath = f"https://raw.githubusercontent.com/{author}/{pluginName}/master/"
    infoPath = rawPath+"/plugin.json"

    global icoPath
    icoPath = ""

    req = requests.get(infoPath)
    if(req.status_code == 200):
        pluginInfo = req.json()
        icoPath = (
            rawPath+pluginInfo["IcoPath"].replace("\\\\", "/").replace("\\", "/"))
    elif(req.status_code == 404):
        infopath = (rawPath+f"{pluginName}/plugin.json")
        req = requests.get(infopath)
        if(req.status_code == 200):
            pluginInfo = json.loads(req.text.encode().decode("utf-8-sig"))
            icoPath = (
                rawPath+pluginInfo["IcoPath"].replace("\\\\", "/").replace("\\", "/"))

    plugin["IcoPath"] = icoPath

with open("plugins.json", "w") as pluginsFile:
    json.dump(plugins, pluginsFile, indent=4)

```

**Comment by taooceros** [comment]
Script to retrieve it.

**Comment by Garulf** [comment]
`rawPath = f"https://raw.githubusercontent.com/{author}/{pluginName}/master/"`

GitHub's default branch is now `main`

**Comment by taooceros** [comment]
> > Should this be used in the CI or are we requiring new plugin submissions to include the file location
> 
> I think Taooceros seems to make that plug-in developers do not have to modify it.

Just let new author indicate their ico link. I make this to find the link of icopath of exist plugin.

**Pull request merged**
