### PR TITLE
New Plugin: Unity projects launcher

### PR DESCRIPTION
**Pull request by Ghost-Miner**
plugin to open unity projects from the kauncher.

exiting plugins for this purpose no longer work and are abandoned or cancelled.

### CODE REVIEW

**Review by jjw24 — CHANGES_REQUESTED** [review]
Could you please publish the release with GitHub action workflow.

**Comment by Ghost-Miner** [comment]
How do you do that? There's no guide for C# and the file I made doesn't seem to work.

**Comment by jjw24** [comment]
You are right, we are actually missing how to setup workflow for .Net plugins.

You almost got it, it's not triggering because the push rule is for master branch, your repo has main branch instead. So just need to change this line https://github.com/Ghost-Miner/Unity-project-launcher-plugin/blob/7ac9204725eef94b32071249d634cc2dd4963396/.github/workflows/Publish%20Release.yml#L5

**Comment by Ghost-Miner** [comment]
so i uploaded a working workflow file, but now it **always** throws "path" not found and either doesnt tell me the full path at all or hides it buried somewhere

**Comment by Ghost-Miner** [comment]
> so i uploaded a working workflow file, but now it **always** throws "path" not found and either doesnt tell me the full path at all or hides it buried somewhere

It looks like i _finally_ got the workflow working.

**Pull request merged**
